### ISSUE TITLE
Conflicts in using apache tika and pdfbox in same project.

### ISSUE THREAD

**Issue by kumbhaj** [Norconex/importer#103]
tika 1.18  and pdfbox 1.4.0.  I have error. I am just using Tika. Is there any way i can use these without removing pdfbox. Any config in tika??
java.lang.NoSuchMethodError: org.apache.pdfbox.pdmodel.PDDocument.load(Ljava/io/InputStream;Ljava/lang/String;Lorg/apache/pdfbox/io/MemoryUsageSetting;)Lorg/apache/pdfbox/pdmodel/PDDocument;
at org.apache.tika.parser.pdf.PDFParser.parse(PDFParser.java:153)
at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143)

**Comment by essiembre** [comment]
That version of Tika 1.18 uses PDFBox 2.x (and the Importer ships with PDFBox 2.x).  Use the PDFBox version shiped with the Importer and you should be fine.
