### ISSUE TITLE
NoSuchMethodError and PDDocument.load

### ISSUE THREAD

**Issue by sobczakt** [Norconex/importer#17]
I have such exception:

> java.lang.NoSuchMethodError: org.apache.pdfbox.pdmodel.PDDocument.load(Ljava/io/InputStream;Ljava/lang/String;Z)Lorg/apache/pdfbox/pdmodel/PDDocument;
>        at org.apache.tika.parser.pdf.EnhancedPDFParser.parse(EnhancedPDFParser.java:162)
>        at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:177)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
        at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120)
        at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:177)
        at com.norconex.importer.parser.impl.AbstractTikaParser$MergeEmbeddedParser.parse(AbstractTikaParser.java:377)
        at com.norconex.importer.parser.impl.AbstractTikaParser.parseDocument(AbstractTikaParser.java:162)
        at com.norconex.importer.Importer.parseDocument(Importer.java:418)
        at com.norconex.importer.Importer.importDocument(Importer.java:314)
        at com.norconex.importer.Importer.doImportDocument(Importer.java:267)
        at com.norconex.importer.Importer.importDocument(Importer.java:195)
        at com.norconex.collector.core.pipeline.importer.ImportModuleStage.execute(ImportModuleStage.java:35)
        at com.norconex.collector.core.pipeline.importer.ImportModuleStage.execute(ImportModuleStage.java:26)
        at com.norconex.commons.lang.pipeline.Pipeline.execute(Pipeline.java:90)
        at com.norconex.collector.http.crawler.HttpCrawler.executeImporterPipeline(HttpCrawler.java:215)
        at com.norconex.collector.core.crawler.AbstractCrawler.processNextQueuedCrawlData(AbstractCrawler.java:475)
        at com.norconex.collector.core.crawler.AbstractCrawler.processNextReference(AbstractCrawler.java:376)
        at com.norconex.collector.core.crawler.AbstractCrawler$ProcessReferencesRunnable.run(AbstractCrawler.java:689)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

I'm trying to use Norconex HTTP Collecotor v2.2.1, and it has dependencies of Norconex Importer v2.3.1 and Apache PDFBox v2.0.0.SNAPSHOT.

EnhancedPDFParser line 162 is:

```java
pdfDocument = PDDocument.load(tstream, password, false);//, preserveMemory);
```

and as I saw PDFBox v2.0.0.SNAPSHOT, PDDocument class really doesn't have such method signature.

**Comment by essiembre** [comment]
Are working from the source, or binary?  Because HTTP Collector 2.2.1 should have the good dependencies packaged with it when used on the command-line.  If you use Maven, I recommend you use the 2.3.0-SNAPSHOT version which is kept up-to-date in regards to PDFBox.   It also has several new features and fixes.  If you need to stick to 2.2.1 for some reason, let me know and I can commit a fix for it.

**Comment by sobczakt** [comment]
I'm working with Maven dependency, so thank you for advice I will try to use 2.3.0-SNAPSHOT

**Comment by essiembre** [comment]
Great, please let me know how that goes before I close this issue.

**Comment by essiembre** [comment]
Just to add: snapshots are produced from the "develop" branch.  So if you want to latest and greatest, I suggest you use that branch.

**Comment by sobczakt** [comment]
When are you going to release version 2.3.0-SNAPSHOT?

I can't build project from "develop" branch because:

```java
gpg: error loading `iconv.dll': The specified module could not be found.
gpg: please see http://www.gnupg.org/download/iconv.html for more information
gpg: NOTE: --use-agent is not available in this version
gpg: keyblock resource `c:/Users/tomasz.sobczak/.gnupg\secring.gpg': file open error
gpg: keyblock resource `c:/Users/tomasz.sobczak/.gnupg\pubring.gpg': file open error
gpg: no default secret key: secret key not available
gpg: signing failed: secret key not available

**Comment by pascaldimassimo** [comment]
In order to deploy the releases to Maven Central, they need to be GPG-signed.  Since you probably just want to build locally, you do not need GPG-signing.  There are a few ways to solve this:

* Easiest: add the following system property to your maven command: ``-Dgpg.skip=true``
* Install GPG on your computer.
* Comment the GPG section of the pom.xml. 
* Use ``mvn package`` as opposed to ``mvn install``.

**Comment by essiembre** [comment]
@sobczakt, were you able to build using one of @pascaldimassimo tips?

**Comment by essiembre** [comment]
Having received no feedback in a while I will close assuming you can build now.  Also, Norconex Importer 2.4.0 was just released.
