### ISSUE TITLE
External transformer  error

### ISSUE THREAD

**Issue by angelo337** [Norconex/importer#71]
hi there:
I am trying to execute an external program on an script, this is the program:

> 
> /usr/bin/convert -density 300 1.pdf -depth 8 1.tiff
> tesseract $1.tiff $2 -l spa

when I try to run the program I am getting this error:

> com.norconex.importer.handler.ImporterHandlerException: External transformer failed. Command: /home/creangel/Downloads/solr/norconex-collector-http-2.8.0-SNAPSHOT/ocr.sh ${INPUT} ${OUTPUT}
	at com.norconex.importer.handler.transformer.impl.ExternalTransformer.transformApplicableDocument(ExternalTransformer.java:443)
	at com.norconex.importer.handler.transformer.AbstractDocumentTransformer.transformDocument(AbstractDocumentTransformer.java:56)
	at com.norconex.importer.Importer.transformDocument(Importer.java:544)
	at com.norconex.importer.Importer.executeHandlers(Importer.java:347)
	at com.norconex.importer.Importer.importDocument(Importer.java:304)
	at com.norconex.importer.Importer.doImportDocument(Importer.java:266)
	at com.norconex.importer.Importer.importDocument(Importer.java:190)
	at com.norconex.collector.core.pipeline.importer.ImportModuleStage.execute(ImportModuleStage.java:37)
	at com.norconex.collector.core.pipeline.importer.ImportModuleStage.execute(ImportModuleStage.java:26)
	at com.norconex.commons.lang.pipeline.Pipeline.execute(Pipeline.java:91)
	at com.norconex.collector.http.crawler.HttpCrawler.executeImporterPipeline(HttpCrawler.java:358)
	at com.norconex.collector.core.crawler.AbstractCrawler.processNextQueuedCrawlData(AbstractCrawler.java:521)
	at com.norconex.collector.core.crawler.AbstractCrawler.processNextReference(AbstractCrawler.java:407)
	at com.norconex.collector.core.crawler.AbstractCrawler$ProcessReferencesRunnable.run(AbstractCrawler.java:789)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.norconex.commons.lang.exec.SystemCommandException: Could not execute command: /home/creangel/Downloads/solr/norconex-collector-http-2.8.0-SNAPSHOT/ocr.sh /tmp/input622119762284705969.tmp /tmp/output850167628537432029.tmp
	at com.norconex.commons.lang.exec.SystemCommand.execute(SystemCommand.java:276)
	at com.norconex.commons.lang.exec.SystemCommand.execute(SystemCommand.java:229)
	at com.norconex.commons.lang.exec.SystemCommand.execute(SystemCommand.java:210)
	at com.norconex.importer.handler.transformer.impl.ExternalTransformer.transformApplicableDocument(ExternalTransformer.java:435)
	... 16 more
Caused by: java.io.IOException: Cannot run program "/home/creangel/Downloads/solr/norconex-collector-http-2.8.0-SNAPSHOT/ocr.sh": error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at com.norconex.commons.lang.exec.SystemCommand.execute(SystemCommand.java:272)
	... 19 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 21 more
INFO  [CrawlerEventManager]           REJECTED_IMPORT: http://www.sic.gov.co/recursos_user/documentos/conceptos/2017/Radicado_13-277605.pdf (com.norconex.importer.response.ImporterResponse@50473fc3)
INFO  [AbstractCrawler] SOC_website: 100% completed (1 proces

could you please help me with this error?
thanks a lot

**Comment by essiembre** [comment]
It looks like the account running the importer does not have permissions to execute your script: 
```
Caused by: java.io.IOException: Cannot run program "/home/creangel/Downloads/solr/norconex-collector-http-2.8.0-SNAPSHOT/ocr.sh": error=13, Permission denied
```
Can this be? Else please share the portion of your config calling your script.

**Comment by angelo337** [comment]
Pascal:
Sure, 

you can see the explanation in [here](https://github.com/Norconex/collector-http/issues/433) 

my script is just 2 lines:

> `convert -density 300 target.pdf -depth 8 -strip -background white -alpha off out.tiff`
> `tesseract out.tiff output`

Regards
